version: "3.9"
services:
  backend:
    build: ./infra/backend
    volumes:
      - ./src/backend:/work
    dns:
      - 8.8.8.8
    tty: true
    ports:
      - 8081:3000
  frontend:
    build: ./infra/frontend
    volumes:
      - ./src/frontend:/work
    dns:
      - 8.8.8.8
    tty: true
    command: yarn dev
    depends_on:
      - mongodb
    networks:
      - default

  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src/frontend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
    dns:
      - 8.8.8.8
    depends_on:
      - frontend
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=test20!
      - MONGO_INITDB_DATABASE=nest_app
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - TZ=Asia/Tokyo

    ports:
      - 27017:27017
    command:
      - mongod
    volumes:
      - db-store:/data/db
      - ./infra/mongodb/init:/docker-entrypoint-initdb.d
    networks:
      - default
      - mongo-express
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: nest_app
      ME_CONFIG_MONGODB_ADMINPASSWORD: test20!
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: test20!
    depends_on:
      - mongodb
    networks:
      - mongo-express
volumes:
  db-store:
networks:
  default:
    driver: bridge
  mongo-express:
    driver: bridge